### ISSUE TITLE
[Feature Request] Charon's Gambit functionality

### ISSUE THREAD

**Issue by abilliontrillionstars** [Master-Bw3/Hex-Studio#33]
When Charon's Gambit is drawn in-game on the grid, the stack and grid are cleared as if the player shift-right-clicked with a staff. can you implement a similar behavior that say, refreshes the page? This is basically just because I have a habit of drawing Charon's.

**Comment by Master-Bw3** [comment]
You can draw `Clear` (`qqqq`) to clear the grid, or `Reset` (`qqqqqa`) to reset everything. Only Meta Patterns (`Clear`, `Reset`, `Backspace`, and `Wrap`) can modify the state of the pattern list, and I intend to keep that distinction.
